### ISSUE TITLE
Added missing block check to peekUnsignedBytes

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#101]

**Comment by RobAustin** [comment]
relates to https://github.com/OpenHFT/Chronicle-Bytes/issues/100

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.25](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.25), [BOM-2.17.236](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.236)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.25](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.25), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
