### ISSUE TITLE
Improve support for BytesMethodReader and MethodId and HexDumpBytes chaining

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#103]

**Comment by JerryShea** [comment]
See https://github.com/OpenHFT/Chronicle-Wire/commit/e4ff2744c8d568448cc92746e7f5aaab04376dea

**Comment by dpisklov** [comment]
Seems to be fixed

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.2](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.2), [BOM-2.19.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.2](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.2), [BOM-2.19.62](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.62)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.2](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.2), [BOM-2.19.63](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.63)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.2](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.2), [BOM-2.19.64](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.64)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
