### ISSUE TITLE
Make sure the global lock in MappedFile is global when using multiple class loaders.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#105]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.37](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.37), [BOM-2.17.387](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.387)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
