### ISSUE TITLE
Added support for byte[], int[], float[], long[], double[] to BytesMarshallable

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#106]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.41](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.41), [BOM-2.17.457](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.457)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
