### ISSUE TITLE
Simplistic suggestion which may resolve old todo

### ISSUE THREAD

**Issue by Cheappie** [OpenHFT/Chronicle-Bytes#108]
https://github.com/OpenHFT/Chronicle-Bytes/blob/30c11b8ba1398b417a6d0148ec8c049723c0398e/src/main/java/net/openhft/chronicle/bytes/VanillaBytes.java#L275

Hello, while I was learning how things work in codebase, I came across some old todo, which was left years ago. I saw some room for improvement in impl, possible change which could be called  'optimisation'. Changes can be found in link mentioned below, what do you think ?

https://github.com/Cheappie/Chronicle-Bytes/pull/1/commits/3d194454c789ad402e18ac6ab978fbda1dd4155f

I may be missing context, so sorry for taking time if that doesn't solve the case.

**Comment by dpisklov** [comment]
@peter-lawrey Peter?

**Comment by RobAustin** [comment]
the main issue here was that java.lang.String#toCharArray creates a new char[]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.4), [BOM-2.19.87](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.87)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.4), [BOM-2.19.90](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.90)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
