### ISSUE TITLE
Feature request: writeUTFΔTruncated

### ISSUE THREAD

**Issue by belousa** [OpenHFT/Chronicle-Bytes#109]
I'd like to request a feature for Bytes (really, RandomDataOutput interface).

Would it be possible to create the string write method that truncates string to fit the available space, rather than throwing an exception when the string does not fit?

Currently, if we need to avoid the exception and we have a string that may be too large, we need to call a substring() on the string we write, creating some garbage. If we have a new writeUTFΔTruncated, we'd be able to solve this situation w/o garbage.

Thank you.

**Comment by peter-lawrey** [comment]
This isn't simple to do the length of a UTF8 character varies and the number bytes to encode the length varies.
It's a much safer option to always ensure you have enough space.
Won't fix.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.43](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.43), [BOM-2.20.67](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.67)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
