### ISSUE TITLE
AbstractBytes.writeSome was not calling ensureCapacity

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#110]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.0](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.0), [BOM-2.19.10](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.10)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
