### ISSUE TITLE
Reinstate MethodWriterBuilder

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#112]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.6](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.6), [BOM-2.19.111](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.111)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.6](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.6), [BOM-2.19.112](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.112)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.6](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.6), [BOM-2.19.116](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.116)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
