### ISSUE TITLE
MappedFile::performRelease closes entities that are the concerns of RandomAccessFile

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#117]
```
closeQuietly(raf.getChannel()); // This is redundant and potentially harmful
closeQuietly(raf);
closeQuietly(fileChannel); // Same here
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
