### ISSUE TITLE
MappedFile: Potential race between acquireByteStore and performRelease

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#118]
It is possible that `performRelease()` and `acquireByteStore()` could be invoked so that stores items are first cleared by `performRelease` but then new ones could be still acquired.

Related to #116

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
