### ISSUE TITLE
Reduced synchronization scope in MappedFile

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#121]
Currently, an unnecessarily large portion of the `MappedFile` code is under synchronization control. Reducing this would increase multi-threaded performance.

**Comment by RobAustin** [comment]
looks good

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
