### ISSUE TITLE
Added a plain elastic on heap Bytes

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#126]
The previous implementation wrapped ByteBuffer making it more expensive than ideal.
This still exists for the cases when an underlying ByteBuffer is still needed.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.40](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.40), [BOM-2.20.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
