### ISSUE TITLE
Chronicle-Bytes Does Not Define an Automatic Module Name

### ISSUE THREAD

**Issue by Teh-Bobo** [OpenHFT/Chronicle-Bytes#127]
When using modular code (my project is in Java 14), I get the following error when compiling:

>Required filename-based automodules detected: [chronicle-bytes-2.19.32.jar]. Please don't publish this project to a public artifact repository!

Adding the Automatic-Module-Name to the pom fixed the issue for me:

><plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Automatic-Module-Name>chronicle.bytes</Automatic-Module-Name>
                        ...

**Comment by dpisklov** [comment]
We don't support Java 14 (and other non-LTS versions). Currently the highest version we support is Java 11. Do you have this issue with Java 11?

**Comment by Teh-Bobo** [comment]
Yes, I get the same message in Java 11. I believe it will happen with any Java 9+ project using modules. The automatic module name just gives the jar file a module name without having to convert the whole codebase to modules.

**Comment by dpisklov** [comment]
So I assume it's a warning rather than error? Our main commercial clients are on Java 8 so we can't use Java9+ modules yet (unless we want to support diverging codebases for which we have no capacity), so we only fix errors but not warnings.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.19.46](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.19.46), [BOM-2.19.259](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.19.259)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
