### ISSUE TITLE
UnsafeText.appendDouble extra zeros

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#128]
@peter-lawrey one for you :)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
