### ISSUE TITLE
Add stack trace if ByteBuffer backed ByteStore ceases to be ByteBuffer backed

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#129]
Some times, said resize event is caused by erroneous code or data and it would be useful to be able to trace code better.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
