### ISSUE TITLE
Reduce test clutter

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#136]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.22](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.22), [BOM-2.20.51](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.51)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
