### ISSUE TITLE
Two tests in BytesTest fail if assertions are off

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#138]
There are a couple of tests which fail when assertions are off.
Internally they expect an exception to be thrown which is not thrown when assertions are off.

**Comment by peter-lawrey** [comment]
This change will have a small performance impact, but the impact of not having it is worse.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.43](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.43), [BOM-2.20.67](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.67)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
