### ISSUE TITLE
MappedFile / MappedBytes should set the file size to the writePosition() on close. Or give a option to set the underlaying RAF file size.

### ISSUE THREAD

**Issue by jonross09** [OpenHFT/Chronicle-Bytes#139]
calling setLength() on the raf from the MappedFile throws a exception under windows, FYI.

It'd be nice to truncate the file to the usable data when closing it w/o having to keep a file handle around to the original file and fix it up after close.

**Comment by jonross09** [comment]
So after some research. this is a well-known issues w/ java and memory-mapped files.

It still would be nice if you'd do the unsafe / "cleaner" hack trick and attempt to set the correct size when shutting down.

**Comment by RobAustin** [comment]
Chronicle-Queue does this already, could you use the net.openhft.chronicle.queue.impl.single.QueueFileShrinkManager from chronicle queue. I'm going to close this issue for now. Please reopen this if it did not work for you.

**Comment by jonross-st** [comment]
I'm not using Chronicle-Queue, and it isn't imported into my project. I'm just using Chronice-Bytes.

So what are my options?

**Comment by dpisklov** [comment]
You can basically reimplement what `QueueFileShrinkManager` does:

```java
        int timeout = 50;
        for (int i = OS.isWindows() ? 1 : 3; i >= 0; i--) {
            if (!queueFile.exists()) {
                LOG.warn("Failed to shrink file as it exists no longer, file=" + queueFile);
                return;
            }
            try (RandomAccessFile raf = new RandomAccessFile(queueFile, "rw")) {
                raf.setLength(writePos);

            } catch (IOException ex) {
                // on microsoft windows, keep retrying until the file is unmapped
                if (ex.getMessage().contains("The requested operation cannot be performed on a file with a user-mapped section open")) {
                    LOG.debug("Failed to shrinking {} to {}, {}", queueFile, writePos, i == 0 ? "giving up" : "retrying");
                    Jvm.pause(timeout);
                    timeout *= 2;
                    continue;
                }
                LOG.warn("Failed to shrink file " + queueFile, ex);
            }
            break;
        }
```

**Comment by jonross-st** [comment]
that worked great. thanks!
