### ISSUE TITLE
Bytes.elasticByteBuffer(int initialCapacity, int maxCapacity) - maxCapacity ignored

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#141]
Problem is with any method that calls `net.openhft.chronicle.bytes.NativeBytesStore#elasticByteBuffer(int, long)`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
