### ISSUE TITLE
PropertyReplacer to be changed to fail hard if is not all property tokens are substituted 

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#143]
The net.openhft.chronicle.bytes.util.PropertyReplacer is used to replace tokens like ${<system.property>} in strings, these strings are typically used as YAML configuration in many of our applications, we should throw an exception if all the tokens are not substituted,  as users can easily miss configured the system properties leaving the application to continue on blindly ( with the wrong configuration ). Currently the net.openhft.chronicle.bytes.util.PropertyReplacer does not throw an exception and it is currently too easy to start the application with properties miss configured.

**Comment by JerryShea** [comment]
Can we throw an exception instead?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.102](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.102), [BOM-2.20.142](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.142)
