### ISSUE TITLE
Use HeapByteStore for BytesStore.from(CharSequence)

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#148]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.104](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.104), [BOM-2.20.153](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.153)
