### ISSUE TITLE
Ensure copy memory throws null pointer exception after close()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#150]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.105](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.105), [BOM-2.20.176](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.176)
