### ISSUE TITLE
Deprecate MethodWriterBuilder.useMethodIds(boolean) for removal

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#153]
@peter-lawrey this method originally authored by you

**Comment by peter-lawrey** [comment]
Yes, perhaps we need more demos. 
@JerryShea  Are you suggesting we should just use them if they have been set?

**Comment by JerryShea** [comment]
@peter-lawrey if we choose to keep it, we should make it true by default IMHO 

I am questioning what is the use for it. Why would we want to turn off using methodIds?

**Comment by peter-lawrey** [comment]
@JerryShea  It was used to programmatically run the same benchmark with and without methodIds however for the purpose of this benchmark we could just duplicate the interface.

**Comment by peter-lawrey** [comment]
There are two examples where an extended interface can be used to select whether @MethodIds should be used if you need it to be switchable. The public one is

https://github.com/OpenHFT/Chronicle-Queue/blob/ea/src/test/java/net/openhft/chronicle/queue/internal/reader/ChronicleHistoryReaderTest.java
