### ISSUE TITLE
NativeBytes: prewrite doesn't perform resize if current write position is beyond the realCapacity

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Bytes#158]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.111](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.111), [BOM-2.20.210](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.210)
