### ISSUE TITLE
Improved error messages for Bytes.write

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#161]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea2](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea2), [BOM-2.21ea25](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea25)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea2](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea2), [BOM-2.21ea26](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea26)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea2](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea2), [BOM-2.21ea27](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea27)

**Comment by JerryShea** [comment]
See also https://github.com/OpenHFT/Chronicle-Bytes/issues/163
