### ISSUE TITLE
Correct way to read a file

### ISSUE THREAD

**Issue by ikorennoy** [OpenHFT/Chronicle-Bytes#165]
Hello! I apologize for my question here not on stackoverflow. I tried to find the answer in unit tests but I could not. And without any guide it's very difficult to understand how to

Could you please tell me or give me some example of proper way to read file with utf8 text line by line? The line length is not known

Now I use the next approach: I map the file using `channel.map(FileChannel.MapMode.READ_ONLY, offset, size)` method and then wrap byteBuffer with `Bytes.wrapForRead(byteBuffer)`

Is there a better way to do this?

Thank you! 
Ilya.

**Comment by peter-lawrey** [comment]
I suggest using `BufferedReader` with UTF_8 encoding unless you have a specific reason to use a memory mapped file.
