### ISSUE TITLE
Added limited support for trivially copyable objects with some transient/reference fields

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#168]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea6](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea6), [BOM-2.21ea47](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea47)
