### ISSUE TITLE
Issue on NativeBytesStore::write from ByteBuffer

### ISSUE THREAD

**Issue by franz1981** [OpenHFT/Chronicle-Bytes#17]
Sent a PR with the fix:
[https://github.com/OpenHFT/Chronicle-Bytes/pull/16](url)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
