### ISSUE TITLE
trivially copyable when base class has a non-primitive field

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#170]

**Comment by JerryShea** [comment]
one for you @peter-lawrey

**Comment by JerryShea** [comment]
Fixed now I believe

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea12), [BOM-2.21ea63](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea63)
