### ISSUE TITLE
Cache the MappedFile size to reduce the impact of checking the capacity

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#171]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea12), [BOM-2.21ea63](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea63)
