### ISSUE TITLE
Bytes.append(double, int dps) rounding

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#174]
see unit test in attached commit

**Comment by rogersimmons** [comment]
A possible concern with always rounding up if the clipped part is exactly 5 is that it introduces a net positive bias.

A common alternative is to round up or down depending on the value of the (retained) digit before the 5 (eg odd digits round up, evens round down) as this pulls the bias towards 0.

It could be useful to have this configurable, but the default should likely be a similar form of fair rounding.

**Comment by JerryShea** [comment]
@rogersimmons yes absolutely. In this case (having reviewed the example again), `Bytes.append(double, precision)` is giving the same results as `Maths.roundN(double, precision)` which is `64.550198` and that is because
```
double d = 64.5501985
double d2 = d * Maths.tens(decimalPlaces)
d2 == 6.455019849999999E7
```
and the 4999 is rounded towards zero

**Comment by JerryShea** [comment]
Just to remind me what the various rounding modes give
```
new BigDecimal("64.5501985").setScale(6, RoundingMode.HALF_EVEN) == 64.550198
new BigDecimal("64.5501985").setScale(6, RoundingMode.HALF_UP) == 64.550199
```
CEILING & UP give same result as HALF_UP

**Comment by peter-lawrey** [comment]
I have changed the behaviour of `BytesStringAppender.append(double value, int digits)` to behave as `Maths.roundNup` rather than `Maths.roundN` There is a notional performance impact of fewer than 6 ns, however, this is expected behaviour.

See https://github.com/OpenHFT/Chronicle-Core/issues/212 for more details and tests
