### ISSUE TITLE
BytesTest::testParseUtf8High fails

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#178]
I have strengthened the `BytesTest::testParseUtf8High` test. Examine why it fails for code `65503`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea45](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea45), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
