### ISSUE TITLE
NativeBytesTest::testAppendCharArrayNonAscii fails

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#179]
The `NativeBytesTest::testAppendCharArrayNonAscii` fails if the actual content of the `Bytes` is asserted by `assertEquals("Δ", b.toString());`

**Comment by peter-lawrey** [comment]
Extended the test for a couple of different UTF8 decoding methods.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea45](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea45), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
