### ISSUE TITLE
Bytes append double with specified number of digits

### ISSUE THREAD

**Issue by drelum** [OpenHFT/Chronicle-Bytes#18]
Bytes currently provides a method to append a long value with a specified number of digits:

default R append(long offset, long value, int digits)

but does not provide a similar 

default B append(double d, int decimalPlaces, int digits)

Why is that? It would be very handy to have overloaded methods dealing with number of digits.

Keep up the excellent work!

André

**Comment by peter-lawrey** [comment]
We are trying to limit the methods ones we have a use case for.

There is a method append(double d, int decimalPlaces) as well
as appendDecimal(long value, int decimalPlaces).

What is your use case this this doesn't do?

The method you indicate is used to implement fixed width numbers for YAML,
something which isn't used yet.

Regards,
   Peter.

**Comment by drelum** [comment]
I currently use the Fixed width append method for long values and I would like to have a fixed width for double values too. I can do it if you think it fits in the class' responsibilities

**Comment by peter-lawrey** [comment]
It would. Can you provide some unit tests which illustrate what you have in
mind?

**Comment by drelum** [comment]
Sorry or the delay. Test Cases:

`

    @Test
    public void testAppendLongRandomPosition() {
        byte[] bytes = "00000".getBytes();
    	ByteBuffer bb = ByteBuffer.wrap(bytes);
        Bytes to = Bytes.wrapForWrite(bb);
        
        to.append(0, 1, 5);
        assertEquals("00001", Bytes.wrapForRead(bb).toString());
    }
    @Test
    public void testAppendLongRandomPosition2() {
        byte[] bytes = "WWWWW00000".getBytes();
    	ByteBuffer bb = ByteBuffer.wrap(bytes);
        Bytes to = Bytes.wrapForWrite(bb);
        
        to.append(5, 10, 5);
        assertEquals("WWWWW00010", Bytes.wrapForRead(bb).toString());
    }
    
    @Test(expected=java.nio.BufferOverflowException.class)
    public void testAppendLongRandomPositionShouldThrowBufferOverflowException() {
        byte[] bytes = "000".getBytes();
    	ByteBuffer bb = ByteBuffer.wrap(bytes);
        Bytes to = Bytes.wrapForWrite(bb);
        
        to.append(0, 1000, 5);
    }
    
    @Test(expected=IllegalArgumentException.class)
    public void testAppendLongRandomPositionShouldThrowIllegalArgumentException() {
        byte[] bytes = "000".getBytes();
    	ByteBuffer bb = ByteBuffer.wrap(bytes);
        Bytes to = Bytes.wrapForWrite(bb);
        
        to.append(0, 1000, 3);
    }
    
    @Test
    public void testAppendDoubleRandomPosition() {
    	byte[] bytes = "000000".getBytes();
        Bytes to = Bytes.wrapForWrite(bytes);
        
        to.append(0, 3.14, 2, 6);
        assertEquals("003.14", Bytes.wrapForRead(bytes).toString());
    }
    
    @Test(expected=java.nio.BufferOverflowException.class)
    public void testAppendDoubleRandomPositionShouldThrowBufferOverflowException() {
    	byte[] bytes = "000000".getBytes();
        Bytes to = Bytes.wrapForWrite(bytes);
        
        to.append(0, 3.14, 2, 8);
    }
    
    @Test(expected=IllegalArgumentException.class)
    public void testAppendDoubleRandomPositionShouldThrowIllegalArgumentException() {
    	byte[] bytes = "000000".getBytes();
        Bytes to = Bytes.wrapForWrite(bytes);
        
        to.append(0, 33333.14, 2, 6);
    }
`

new method for double in BytesInternal

`

     public static void appendDecimal(@NotNull RandomDataOutput out, long num, long offset, int    decimalPlaces, int width) throws IORuntimeException, IllegalArgumentException,  BufferOverflowException {
    	if (decimalPlaces == 0) {
            append(out, offset, num, width);
            return;
        }

        byte[] numberBuffer = NUMBER_BUFFER.get();
        int endIndex;
        if (num < 0) {
            if (num == Long.MIN_VALUE) {
                numberBuffer = MIN_VALUE_TEXT;
                endIndex = MIN_VALUE_TEXT.length;
            } else {
                out.writeByte(offset++, (byte) '-');
                num = -num;
                endIndex = appendLong1(numberBuffer, num);
            }
        } else {
            endIndex = appendLong1(numberBuffer, num);
        }
        int digits = numberBuffer.length - endIndex;
        
        
        
        if (decimalPlaces >= digits) {
        	int numDigitsRequired = 2+decimalPlaces;
        	if (numDigitsRequired > width)
        		throw new IllegalArgumentException("Value do not fit in " + width + " digits");
            out.writeUnsignedByte(offset++, '0');
            out.writeUnsignedByte(offset++, '.');
            while (decimalPlaces-- > digits)
                out.writeUnsignedByte(offset++, '0');
            out.write(offset++, numberBuffer, endIndex, digits);
            return;
        } else {
        	int numDigitsRequired = digits+1;
        	if (numDigitsRequired > width)
        		throw new IllegalArgumentException("Value do not fit in " + width + " digits");
        }
        
       
        while (width-- > (digits+1)) {
            out.writeUnsignedByte(offset++, '0');
        }
        

        int decimalLength = numberBuffer.length - endIndex - decimalPlaces;
        out.write(offset, numberBuffer, endIndex, decimalLength);
        offset+=decimalLength;
        out.writeUnsignedByte(offset++, '.');
        out.write(offset++, numberBuffer, endIndex + decimalLength, digits - decimalLength);
    }
`


new method for long in BytesInternal

`

     public static void append(@NotNull RandomDataOutput out, long offset, long num, int width) throws IORuntimeException, IllegalArgumentException, BufferOverflowException {
        boolean negative = num < 0;
        num = Math.abs(num);

        for (int i = width - 1; i > 0; i--) {
            out.writeByte(offset + i, (byte) (num % 10 + '0'));
            num /= 10;
        }
        if (negative) {
            if (num != 0)
                numberTooLarge(width);
            out.writeByte(offset, '-');

        } else {
            if (num > 9)
                numberTooLarge(width);
            out.writeByte(offset, (byte) (num % 10 + '0'));
        }
    }   

`

at last, RandomDataOutput has two new methods

`
´

    @NotNull
    default R append(long offset, long value, int digits) throws BufferOverflowException,  llegalArgumentException, IORuntimeException {
        BytesInternal.append(this, offset, value, digits);
        return (R) this;
    }

    @NotNull
    default R append(long offset, double value, int decimalPlaces, int digits) throws BufferOverflowException, IORuntimeException {
        if (decimalPlaces < 20) {
            double d2 = value * Maths.tens(decimalPlaces);
            if (d2 <= Long.MAX_VALUE && d2 >= Long.MIN_VALUE) {
            	BytesInternal.appendDecimal(this, Math.round(d2), offset, decimalPlaces, digits);
                return (R) this;
            }
        }
        BytesInternal.append((StreamingDataOutput) this, value);
        return (R) this;
    }

`

**Comment by peter-lawrey** [comment]
Do you want to issue this as a Pull Request?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
