### ISSUE TITLE
Document the ByteStore vs Bytes abstraction

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#181]
please document the reason for the "ByteStore vs Bytes abstraction. At a casual glance, they both implement the Bytes interface. What’s the abstraction for, and how should we prefer one over the other."

**Comment by RobAustin** [comment]
somewhat of an answer is below: ( please illustrate this with an example )

In summary, you can have a Bytes per thread, each thread has its own read position, read limit, write position write limit, but they use the same underlying net.openhft.chronicle.bytes.BytesStore. Allowing multiple threads to read the same data, but each thread with its own cursor, to a shared data structure, Hence you should favor using Bytes over BytesStore as it gives you this cursor access, via the  RandomCommon interface, see net.openhft.chronicle.bytes.RandomCommon

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea45](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea45), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
