### ISSUE TITLE
Document the difference between bytesForRead() and bytesForWrite()

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#182]
Question: What’s the difference between bytesForRead() and bytesForWrite(). The interfaces they return barely differ at all. Both have all the write methods on them, and  they seem to work so bytesForRead() doesn’t seem to be handing back a read-only buffer.  

Answer: 

Yes, they are essentially the same, the only difference is to do with the read position and write positions, when you call bytes. bytesForRead() it sets the read position to the start of this data structure and the readLimit, to the end. When you call  bytesForWrite() it sets the writePosition to the start of this data structure.

Please create an example and add some doco to the readme, also please update and improve the Javadoc around this.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea46](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea46), [BOM-2.21ea114](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea114)
