### ISSUE TITLE
Optimise writeStopBit(char) for high values

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#183]

**Comment by peter-lawrey** [comment]
Values (char) -127 to (char) -1 can be treated as signed values reducing their size from 3 bytes to 2.

**Comment by peter-lawrey** [comment]
(char) -1 is used in FIX for unset characters

**Comment by JerryShea** [comment]
@peter-k-lawrey is this forwards/backwards compatible with existing serialised data?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea44](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea44), [BOM-2.21ea110](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea110)
