### ISSUE TITLE
Optimise for null String and Bytes

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#184]
Bytes wasn't optimized for having lots of null values for read8bit Bytes and Strings.
These were slower than reading a 1 character string as a result.

C.F. #183

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea44](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea44), [BOM-2.21ea110](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea110)
