### ISSUE TITLE
capacity() and writeLimit() differs in new Bytes object

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#185]
As indicated by `BytesTest::capacityVsWriteLimitInvariant` and `BytesTest::isClear`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea45](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea45), [BOM-2.21ea113](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea113)
