### ISSUE TITLE
Add address checking using assert

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#187]
Many memory abstractions, for example, `HeapBytesStore`, lacks address range checking. We should add assertions to these accessors to be able to capture potential problems at least when running tests.

**Comment by minborg** [comment]
We should also add documentation that states that these objects are unsafe to use.

**Comment by peter-lawrey** [comment]
`HeapByteStore` is intended to be wrapped using `Bytes`.
For this reason, it probably shouldn't be public, however extra bounds checks should be redundant.
Can you confirm if there are any cases where these bounds can be exceeded via one of the Bytes.

NOTE: The use of off-heap memory has the same level of protection.

**Comment by peter-lawrey** [comment]
Covered by #186

**Comment by minborg** [comment]
See the `feature/assertions` of cases where there is an out-of-bounds use via a back-door.

**Comment by minborg** [comment]
I think we should add assert protection on all unprotected memory models. This would allow us to pick up errors not only in the Bytes library but in others as well. This will have zero performance cost.

**Comment by minborg** [comment]
I have created a convenience class for easy bounds checking with assert. See the branch

**Comment by peter-lawrey** [comment]
@minborg I have seen you added some checks, is there anything more to do.

**Comment by minborg** [comment]
Yes, there are many places we could add checking. I could take a swing at it.

**Comment by minborg** [comment]
When I added some asserts when doing the initial checks (which we rolled back because they were not for free at that time), I uncovered some potential problems. I think this is worth revisiting.

**Comment by minborg** [comment]
I think we covered enough in the efforts above. Let's review the rest later.
