### ISSUE TITLE
Improve performance of read8bit/write8bit

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#188]
Currently, these are slower than readUtf8/writeUtf8 as they haven't been as optimized.

**Comment by peter-lawrey** [comment]
A direct comparison of read8bit/write8bit with readUtf8/writeUrf8 showed that 8 bit was faster as expected, further investigation is needed.

**Comment by peter-lawrey** [comment]
To get reliable results for this we may need to use a C library.

**Comment by RobAustin** [comment]
I assume this can now be closed
