### ISSUE TITLE
HeapBytesStore checking wrong offset

### ISSUE THREAD

**Issue by drelum** [OpenHFT/Chronicle-Bytes#19]
Shouldn´t HeapBytesStore line 336 and 345 check offsetInRDO instead of offset?

In other words, boths lines should be changed from:
writeCheckOffset(offset, length);

to:
writeCheckOffset(offsetInRDO, length);

**Comment by peter-lawrey** [comment]
Yes, it should. Would you like to issue a pull request or I can make the
change?

**Comment by drelum** [comment]
I am fixing it along with the new append double feature ok?

**Comment by peter-lawrey** [comment]
That sounds good to me. Be sure to include unit tests

Thank you,  Peter.

**Comment by drelum** [comment]
When is the next release due?

**Comment by peter-lawrey** [comment]
We plan to do a release of Queue which means releasing Byte within the next
week.

**Comment by drelum** [comment]
thanks

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
