### ISSUE TITLE
parseLong, parseLongDecimal, parseFloat and parseDouble to set lastNumberHasDigits() if it had any digits

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#190]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea46](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea46), [BOM-2.21ea114](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea114)
