### ISSUE TITLE
Added support for lock/tryLock to the underlying file channel for AbstractReference

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#191]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea46](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea46), [BOM-2.21ea114](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea114)
