### ISSUE TITLE
Add a test

### ISSUE THREAD

**Issue by jkolobok** [OpenHFT/Chronicle-Bytes#193]
Add a test to Chronicle-Bytes for this use case e.g.

        final String SYMBOL_STR = "LCOM1";
        final Bytes SYMBOL = Bytes.allocateDirect(SYMBOL_STR.length());
        SYMBOL.clear();
        SYMBOL.append(SYMBOL_STR);

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea48](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea48), [BOM-2.21ea131](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea131)
