### ISSUE TITLE
Improve performance for on heap memory copies.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#195]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21ea48](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21ea48), [BOM-2.21ea131](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21ea131)
