### ISSUE TITLE
Appending some really small doubles throws an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Bytes#199]
From a client:

> NativeBytes<Void> bytes = Bytes.allocateElasticDirect(512);
>
> bytes.append(4.460177372466667E-16);
>
> I did a check of other numbers, and it looks okay at 1E-11, but between 1E-12 & 1E-18, there are a heaps of doubles that cause this exception.

**Comment by peter-lawrey** [comment]
Agree that this doesn't make sense.

**Comment by JerryShea** [comment]
This fix ([in core](https://github.com/OpenHFT/Chronicle-Core/commit/08da4db739bc3832a17ff6681e1b705f2b7f6b0a)) was released in bom 2.21ea65

**Comment by peter-lawrey** [comment]
The Native allocater has an implementation which fails this test.
