### ISSUE TITLE
Provide a property configurable <size> to BytesInternal.SI = new StringInternerBytes(<size>)

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#205]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea20](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea20), [BOM-2.23ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea72)
