### ISSUE TITLE
Trivially copyable not supported on Zing - throw UnsupportedOperationException

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#207]
2 tests are consistently failing:

* `BytesUtilTest.triviallyCopyable2 net.openhft.chronicle.bytes`
* `BytesFieldInfoTest.lookup net.openhft.chronicle.bytes.internal`

@peter-k-lawrey if you don't get the chance to look today I can fix tomorrow

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21.90](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21.90), [BOM-2.21.238](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.238)
