### ISSUE TITLE
lastest release Maven Central 

### ISSUE THREAD

**Issue by drelum** [OpenHFT/Chronicle-Bytes#21]
Hi. I dont see latest release in http://mvnrepository.com/artifact/net.openhft/chronicle-bytes

Could you check? 

Thank you

André

**Comment by drelum** [comment]
i was able to download it from maven central, so my mistake. closing it

**Comment by peter-lawrey** [comment]
Mvnrepository is a bit behind maven search which both update some time
after it is actually available.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
