### ISSUE TITLE
Add features to support NativeBytesStore being internalized

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#210]
- [x] Static constructor

Libraries like Salt is creating native BytesStore instances. It would be good if we add a static method:

`NativeStore.nativeBytesStore(CharSequence text) that would just delegate to `net.openhft.chronicle.bytes.internal.NativeBytesStore.from(text)`, This way, we can easily create such instances without referring to internal classes.

- [ ] Trait for NativeBytesStore

In libraries like Map, we are "uninit" native memory but since `NativeByteStore` was internalized, it is not possible to invoke these methods without externally referring to an internal class. To fix this, we could add a trait "NativeUninitializable" or something like that that exposes the `uninit()` method. Another alternative is to add this method as a new default method in `BytesStore` and throw an exception if not supported. I think an `if (bytes instanceof NativeUninitializable)` would be better.

**Comment by minborg** [comment]
`NativeUninitializable` could also include the `init()` method and so, it should be called something else like `NativeInitializable`

**Comment by JerryShea** [comment]
Yep we already have e.g. `net.openhft.chronicle.bytes.BytesStore#nativeStore` i.e. BytesStore has static factory methods
