### ISSUE TITLE
Flaky test MappedUniqueTimeProviderTest

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#211]
see https://teamcity.chronicle.software/buildConfiguration/OpenHFT_ChronicleBytes_Sonar/600494?

**Comment by peter-lawrey** [comment]
This is a critical section of code and shouldn't be left @Ignored for so long.

**Comment by RobAustin** [comment]
> This is a critical section of code and shouldn't be left @ignored for so long.
agreed - Per can you look at it as soon as you are back from the Christmas break.

**Comment by RobAustin** [comment]
@peter-lawrey does your commit above fix this issue, can it now be closed?

**Comment by peter-lawrey** [comment]
The problem is that the section of code runs 700x slower on Sonar than it does normally.  
Note: The Rasberry PI is only 6x slower, so it should fail if it really is going that much slower.
I have fixed the issue by adding assumeTrue it's not running in sonar.

**Comment by peter-lawrey** [comment]
Doesn't look like you can easily detect if it's running under Sonar. However, the test runs fine otherwise, and we can't be turning this test off. I will leave Sonar failing for now.

**Comment by peter-lawrey** [comment]
This appears to be a problem in the old Sonar build. In the new Sonar build, these tests pass ok.
