### ISSUE TITLE
AbstractReference to hold reference to underlying BytesStore to reduce churn esp. MappedBytes

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#213]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21.94](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21.94), [BOM-2.21.257](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.257)
