### ISSUE TITLE
Refactor Mapped* classes to support an alternative implementation

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#214]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea3](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea3), [BOM-2.22ea23](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea23)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea5), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea3](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea3), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
