### ISSUE TITLE
Fix inconsistencies in how MappedFiles are cleaned up

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#215]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea3](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea3), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
