### ISSUE TITLE
MappedByteStore to use one bytesStore field instead of two.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#219]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea4), [BOM-2.22ea29](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea29)
