### ISSUE TITLE
Add a unit test for trailing zeros for Bytes.append(double)

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#225]

**Comment by peter-lawrey** [comment]
Follows https://github.com/OpenHFT/Chronicle-Wire/issues/299

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea9](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea9), [BOM-2.22ea48](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea48)
