### ISSUE TITLE
Bytes.writeSkip should be able to accept -ve numbers

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#226]
Customer has reported that MappedBytes.writeSkip used to accept negative numbers but that between bytes 2.20.82 -> 2.21ea61 it has been changed to throw an exception if you give it a negative number.

We call Bytes.writeSkip with a -ve number in a number of places in our codebase so this has to be classed as a bug.

We need to update tests and javadoc for this and readSkip too.

**Comment by JerryShea** [comment]
@minborg this is something to consider as part of your work to improve the method contracts and tests

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.21.91](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.21.91), [BOM-2.21.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.21.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea12), [BOM-2.22ea57](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea57)
