### ISSUE TITLE
Ensure the underlying capacity is large enough if the readLimit/WritePosition is moved

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#245]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea10](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea10), [BOM-2.22ea49](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea49)
