### ISSUE TITLE
Improve hashCode()/equals() consistency

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#252]
There are several places in which concrete and abstract classes override either `hashCode()` and `eqals()`. For example, `MappedBytesStore` and `PointerBytesStore` do not override `equals()` even though `hashCode()` is overridden via `AbstractBytesStore`

Generally, we should change the behaviour so that `hashCode()` and `equals()` inherit directly from Object. This will have the benefit that customers no longer can use `Bytes` mutable state when using Maps and Sets. Imagine using `Bytes` for keys in a `Map` or in a set `Set` and then `Bytes` objects are reused and mutated...  That way a `Set<CharSequence>` can have the content [“A”, “A”, “A”] for example.

This will also take care of the problem when these methods are invoked on a released object. It will also improve performance, especially for `Bytes` with large content. This would make `Bytes` behave the same way as `StringBuilder`.

If we cannot use `Object::hashCode`/`Object::equals`, then we should throw an exception if the object is released or else we could potentially crash the JVM (e.g. if a user holds a reference to a `Bytes` object which was previously released)

**Comment by JerryShea** [comment]
This is a big change - we need to consider and possibly reach out to customers

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea12), [BOM-2.22ea57](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea57)
