### ISSUE TITLE
Improve handling of released resources for methods inherited from Object

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#253]
Some methods might create problems if applied to objects which have previously been released. This issue is about creating tests that assure compliance in this perspective.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea12), [BOM-2.22ea57](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea57)
