### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#257]
`BytesJavaDocComplianceTest::beforeEach` did not release `Bytes` created.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea12), [BOM-2.22ea57](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea57)
