### ISSUE TITLE
Improve handling of released resources for some less performance sensitive operations

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#266]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea12), [BOM-2.22ea57](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea57)
