### ISSUE TITLE
Add a public method that compares the contents of two ByteStores so that Bytes.equals() can be replaced

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#268]
Now that Bytes.equals() might have another behaviour

**Comment by minborg** [comment]
This can be made by exposing the `BytesInternal::contentEqual` method in the public API.

**Comment by minborg** [comment]
All tests should use this method rather than `assertEquals(bytes0, bytes1)`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea12), [BOM-2.22ea57](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea57)
