### ISSUE TITLE
In NativeBytes.resize(), should we silently consume IllegalStateException?

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Chronicle-Bytes#27]
Why https://github.com/OpenHFT/Chronicle-Bytes/blob/master/src/main/java/net/openhft/chronicle/bytes/NativeBytes.java#L159-L161?

In case of ISE, it seems the data will be vanished (or corrupted), and we silently continue working. Shouldn't it better just leave ISE for the caller (and then `this.bytesStore` won't be replaced and released)?

**Comment by peter-lawrey** [comment]
At one point I made a few exception checked (see a sub module in core) to
ensure unchecked exceptions were handled correctly. In this case the catch
might have been added incorrectly.  If so, it should be wrapped with
AssertionError if it should never happen.

Need to review it.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
