### ISSUE TITLE
Rename some generic variables to adhere to common standards

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#271]
Rename `Underlying` to `U`
Rename `ACS` to `T`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea12), [BOM-2.22ea57](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea57)
