### ISSUE TITLE
Specify and test cursor operations on a closed resource

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#274]
What is `readPosition()` on a closed resource, for example?

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea5), [BOM-2.23ea27](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea27)
