### ISSUE TITLE
Tried to serialize BigDecimal but there is no support for it in BytesMarshaller

### ISSUE THREAD

**Issue by vasilemihali** [OpenHFT/Chronicle-Bytes#29]
Not actually a bug, more like an extension to support common types from Java.

I'am using version 1.7.15 and I had to write my own implementation for BigDecimal serialization, can you please provide build-in support for it? thanks.

**Comment by peter-lawrey** [comment]
Add support for writing/reading text and binary formats.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
