### ISSUE TITLE
Consistently introduce @NonNegative across the public API

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#290]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea5), [BOM-2.23ea27](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea27)
