### ISSUE TITLE
Remove @NonNull for primitive arrays

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#291]
Instead, this should be explicitly asserted where appropriate and documented.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea5), [BOM-2.23ea27](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea27)
