### ISSUE TITLE
Change the hash of an empty key to be Long.MIN_VALUE instead of 0.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#296]
This makes it easier to handle hash collections for empty keys

This value was chosen to minimise the impact as `(int) Long.MIN_VALUE == 0` and `Long.MIN_VALUE << 1 == 0`

**Comment by minborg** [comment]
Will this change make Map and other existing hash-based algorithms fail for existing data?

**Comment by peter-lawrey** [comment]
Behaviour reverted.
