### ISSUE TITLE
Add other methods with hoisted boundary checks

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#297]
For example `startsWith` and 'compareUtf8' in `BytesInternal`

**Comment by minborg** [comment]
We need better support to do this. Suggest closing this issue and revisit on a larger update of the lib

**Comment by minborg** [comment]
We could use `HasUncheckedRandomDataInput`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea6](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea6), [BOM-2.23ea37](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea37)
