### ISSUE TITLE
Unrelated synchronization

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#299]
In the classes `SingleMappedFile` and `MappedFile` we synchronize on the `cannonicalPath` which is an internalized String making sure it remains unique for the JVM. 

However, objects which are pooled and potentially reused should not be used for synchronization. If they are, it can cause unrelated threads to deadlock with unhelpful stacktraces. Specifically, String literals and boxed primitives such as Integers should not be used as lock objects because they are pooled and reused.

If there are other libraries doing the same, they will interfere, including other Chronicle libraries.

We could create a wrapper class and synchronize on instances of that class instead.

**Comment by minborg** [comment]
This is related to https://github.com/OpenHFT/Chronicle-Bytes/issues/298

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea13](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea13), [BOM-2.22ea69](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea69)
