### ISSUE TITLE
SingleMappedBytes.write(final long writeOffset, @NotNull final RandomDataInput bytes, long readOffset, final long length) should use the writeOffset not the writePosition

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#310]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea14](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea14), [BOM-2.22ea71](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea71)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea14](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea14), [BOM-2.22ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea72)
