### ISSUE TITLE
Remove issues flagged as Security Hotspots

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#316]
- [ ] `NativeBytes::ensureCapacity` invokes `Exception::printStackTrace`

- [ ] `ChunkedMappedFile` is using a shared tmp resource

**Comment by JerryShea** [comment]
printStackTrace in this case is completely legit so we should disable the warning IMO

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea14](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea14), [BOM-2.22ea71](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea71)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea14](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea14), [BOM-2.22ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea72)
