### ISSUE TITLE
ObjectInput/OutputStream and standard Java serialization interop with Bytes/Wire improvement proposal

### ISSUE THREAD

**Issue by leventov** [OpenHFT/Chronicle-Bytes#32]
I have an idea how it could be improved significantly compared to what we currently do (creating a new ObjectInputStream/OutputStream on each operation):

Copy ObjectInputStream from Android Open Source Project (not GPL but Apache licensed, unlike OpenJDK) and modify it to make reusable. Very minor modifications are needed, that is expose the ability to clear the sets of encountered references and classes since the start of the stream.  Also their internal buffering could be removed, because it assumes arbitrary InputStream/OutputStream as a backend, but for Bytes backend buffering is not needed.

Then cache this reusable class in ThreadLocal inside Bytes or Wire.

**Comment by peter-lawrey** [comment]
That is a good idea.
