### ISSUE TITLE
Implement subSequence(start, end) in Bytes

### ISSUE THREAD

**Issue by glukos** [OpenHFT/Chronicle-Bytes#324]
```
    /**
     * Not supported.
     */
    @NotNull
    @Override
    default CharSequence subSequence(int start, int end) {
        throw new UnsupportedOperationException("todo");
    }
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22ea17](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22ea17), [BOM-2.22ea79](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22ea79)
