### ISSUE TITLE
Add lenient checking to readByte()

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Bytes#329]
Right now, `readShort()` to `readDouble()` have lenient checking in `AbstractBytes`, but `readByte()` does not and will always return 0.

Let's make it aware of `lenient` setting. The rest of unchecked/unsigned byte methods which return -1 may remain the same.

**Comment by alamar** [comment]
Will do in 2.23

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea0](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea0), [BOM-2.22.129](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.129)
