### ISSUE TITLE
Add support for encryption

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#33]

**Comment by peter-lawrey** [comment]
Added tests

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
