### ISSUE TITLE
HexDumpBytes.zeroOut needs to assume the offsets are 32-bit

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#336]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea0](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea0), [BOM-2.22.129](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.129)
