### ISSUE TITLE
AbstractReference uses existing offset to trigger initialisation of newly assigned BytesStore

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Bytes#342]
When `AbstractReference#bytesStore(bytes, offset, length)` is called the reference calls `BytesStore#readInt` with its existing offset value. This is not guaranteed to be in the range for the new bytes.

This is the root cause of https://github.com/OpenHFT/Chronicle-Queue/issues/1025

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea3](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea3), [BOM-2.23ea13](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea13)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22.22](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22.22), [BOM-2.22.133](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.133)
