### ISSUE TITLE
copyTo bug leads to inefficient double loop

### ISSUE THREAD

**Issue by randomanderson** [OpenHFT/Chronicle-Bytes#36]
In `RandomDataInput`, the default implementation has a bug where it loops twice:

        int len = (int) Math.min(bb.remaining(), readRemaining());
        int i;
        for (i = 0; i < len - 7; i += 8)
            bb.putLong(i, readLong(start() + i));
        for (i = 0; i < len; i++)
            bb.put(i, readByte(start() + i));
        return len;

I think the intention was to copy 8 bytes at a time using `putLong`, then copy the remaining using `put`.  The current loop copies 8 at a time, then copies them all again 1 at a time.

**Comment by peter-lawrey** [comment]
The second i = 0 is a bug. Do you want to issue a PR?

**Comment by leventov** [comment]
Reviewed similar places, found a couple more problems:
 - In `VanillaBytes.append8bitNBS_S()`, double `i` assignment and should be `i < length -3`
 - In `BytesInternal.findByte()`, looping until `Integer.MAX_VALUE` looks very suspicious, should instead use some limit from the `bytes` object

**Comment by randomanderson** [comment]
Coming back to this, the first `i = 0 ` is a bug too!  Instead of copying to the ByteBuffer, it overwrites the buffer.  The first for...loop should start at `i = bb.position`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
