### ISSUE TITLE
Fixed thread safety issue with StringInternerBytes

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#363]
Relates to support ticket number 651

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea7](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea7), [BOM-2.23ea44](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea44)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22.30](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22.30), [BOM-2.22.174](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.174)
