### ISSUE TITLE
Document MappedBytes

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#368]
`MappedBytes`avoids bloating the virtual memory usage by releasing the chunks that are not used, retaining only the most recently used one. This should be documented.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea9](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea9), [BOM-2.23ea61](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea61)
