### ISSUE TITLE
StreamingDataInput.readWithLength doesn't work for length > 7

### ISSUE THREAD

**Issue by KenCoder** [OpenHFT/Chronicle-Bytes#370]
I'm new to Chronicle, but I think this line should have `(length - 7)/8` as the limit, otherwise the method reads more bytes than are written by writeWithLength. 

https://github.com/OpenHFT/Chronicle-Bytes/blob/8c6a74a41937cffcc1007ba797c474d0d17b11c5/src/main/java/net/openhft/chronicle/bytes/StreamingDataInput.java#L550

**Comment by peter-lawrey** [comment]
You are right that this is wrong.

**Comment by peter-lawrey** [comment]
Thank you for reporting this

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea9](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea9), [BOM-2.23ea61](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea61)
