### ISSUE TITLE
Improve NoBytesStore

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#374]
There are some problems with this class:

- [ ] `NoBytesStore` should be immutable but shares a mutable state via `addressForRead()`, `addressForWrite()` and `addressForWritePosition()`
- [ ] It is using raw types
- [ ] `copy()` does not return a copy and copy is not fully specified
- [ ] `bytesForRead()` returns a new `Bytes` object whereas `bytesForWrite()` does not
- [ ] it is not tested
- [ ] `copyTo(@NotNull OutputStream out)` is not overridden
- [ ] `zeroOut` is not overridden
- [ ] The class javadoc says it can be resized
- [ ] and more...

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea10](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea10), [BOM-2.23ea68](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea68)
