### ISSUE TITLE
create table with system properties in Chronicle-Bytes

### ISSUE THREAD

**Issue by j4sm1ne96** [OpenHFT/Chronicle-Bytes#377]

**Comment by j4sm1ne96** [comment]
@minborg I have added in the system properties. Forough recommended talking to you about the 'description' section of the system properties for this repository

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea20](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea20), [BOM-2.23ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea72)
