### ISSUE TITLE
update figure 1 in ReadMe 

### ISSUE THREAD

**Issue by foroughgoudarzi** [OpenHFT/Chronicle-Bytes#379]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea10](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea10), [BOM-2.23ea68](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea68)
