### ISSUE TITLE
Improve handling of deprecated RDI methods

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#382]
Some depending libraries and presumably user code will flag for deprecated methods. Improve this and remove the source of warnings.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea10](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea10), [BOM-2.23ea68](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea68)
