### ISSUE TITLE
Bytes: Writing an array of length zero does not create new ByteStore

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Bytes#384]
There is a shared singleton for empty ByteStores. However, there are cases where a real, unshared, ByteStore is assumed to exist. Therefore, even writing an array of length zero should trigger a replacement of the shared singleton.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea10](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea10), [BOM-2.23ea68](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea68)
