### ISSUE TITLE
Performance optimisation writing to mapped file

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#391]
As `realWriteRemaining` default implementation lead to an expensive system call

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea20](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea20), [BOM-2.23ea72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea72)
