### ISSUE TITLE
Optimise ensureCapacity

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#398]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea22](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea22), [BOM-2.23ea80](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea80)
