### ISSUE TITLE
UncheckedNativeBytes does not extend NativeBytes

### ISSUE THREAD

**Issue by Neiko2002** [OpenHFT/Chronicle-Bytes#4]
The UncheckedNativeBytes class does not extend the NativeBytes class making them not elastic. I was trying to get elastic unchecked Bytes with Bytes.allocateElasticDirect(capacity).unchecked(true), this way I would have good performance and still the ability to grow my buffer manually.

Is this implementation a design decision or a mistake?

**Comment by peter-lawrey** [comment]
Unchecked bytes gets its performance boost by not checking bounds in all
cases.

The elastic buffer only resized when the bounds are exceeded but since
unchecked doesn't check this, there is no guarantee it will happen.

**Comment by Neiko2002** [comment]
I know, but it would be nice to call resize() or writeCheckOffset() manually to grow the buffer even if all the read/write method wont check size anymore. e.g. Let's assume I want to add 100 more elements to my existing buffer as fast as possible. Uncheck is true to boost the performance and now I would like to grow my buffer by 100*objectSize bytes. What would be the best was to do this?

**Comment by peter-lawrey** [comment]
That makes sense. I will add a jira to do this.

**Comment by peter-lawrey** [comment]
Bytes now has an ensureCapacity(size) which can be used to increase the size (though not decrease it) 

Note: it may make the size larger than you ask for, for efficiency. e.g. if you add one byte each time.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
