### ISSUE TITLE
Drop references to chronicle-enterprise-snapshots and chronicle-enterprise-release in pom.xml

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#405]

**Comment by peter-lawrey** [comment]
Do any open source libraries need a reference to enterprise releases or snapshots?

**Comment by alamar** [comment]
Only if they happen to use any optional enteprise dependencies or plugins.

**Comment by RobAustin** [comment]
closing as this was done
