### ISSUE TITLE
Bytes.wrapForWrite(ByteBuffer).write() corrupts heap

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Bytes#410]
I am attaching a test case based on Network SSL test I was looking into.

I suspect this is due to

            BytesStore<?, ByteBuffer> bs = BytesStore.wrap(byteBuffer);
            try {
                Bytes<ByteBuffer> bbb = bs.bytesForWrite();
                bbb.writePosition(byteBuffer.position());
                bbb.writeLimit(byteBuffer.limit());
                return bbb;
            } finally {
                bs.release(INIT); // what happens to bbb at this point?
            }

**Comment by alamar** [comment]
#411

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea26](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea26), [BOM-2.23ea112](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea112)
