### ISSUE TITLE
Consider resetting thread usage when bytes object is cleaned

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Bytes#425]
The following snippet is prevalent across our code:
```
    static class Notifier {
        Report er = new Report(Bytes.allocateElasticOnHeap());

        ... constructed in main thread, used in dedicated thread only...

    Report(Bytes bytes) {
        this.bytes = bytes;
        this.bytes.clearAndPad(256L);
    }
```

It will cause single thread checker warningd

On the other hand, binding bytes to thread is likely a heavy (and garbage-producing) operation, so it's possible that code which uses and cleans a small Bytes instance in a loop will become prohibitively slow if we simple `clearUsedByThread()` on every

**Comment by RobAustin** [comment]
@peter-lawrey do you have a veiw on this issue ?

**Comment by alamar** [comment]
Closing as it seems we are generally past this issue.
