### ISSUE TITLE
Exponent is ignored when it is explicitly positive

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Bytes#438]
```
        buf.append("1E-2").parseDouble()); // works
        buf.append("1E+2").parseDouble()); // returns 1.0
```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23ea29](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23ea29), [BOM-2.23ea121](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23ea121)
