### ISSUE TITLE
The CanonicalPath should not be unique when run with different classLoaders in the same JVM

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#443]
When running in different classloaders,  the following issue was found

![image](https://user-images.githubusercontent.com/6506056/191758556-b3c9de20-1b54-4837-87a7-34098e8b2292.png)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23.31](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23.31), [BOM-2.23.126](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.126)
