### ISSUE TITLE
UnsafeRWObjectTest fails on Mac OSX with Intel processor

### ISSUE THREAD

**Issue by pcoppinger** [OpenHFT/Chronicle-Bytes#450]
Received the following error with build from version 2.24ea0-SNAPSHOT:

[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.302 s <<< FAILURE! - in net.openhft.chronicle.bytes.UnsafeRWObjectTest
[ERROR] net.openhft.chronicle.bytes.UnsafeRWObjectTest.longObject  Time elapsed: 0.078 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<00000000 0[1 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00 ········ ········
00000010 03 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00 ········ ········
00000020 05 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00 ········ ········
00000030 07 00 00 00 00 00 00 00  08] 00 00 00 00 00 00 0...> but was:<00000000 0[8 00 00 00 00 00 00 00  02 00 00 00 00 00 00 00 ········ ········
00000010 03 00 00 00 00 00 00 00  04 00 00 00 00 00 00 00 ········ ········
00000020 05 00 00 00 00 00 00 00  06 00 00 00 00 00 00 00 ········ ········
00000030 07 00 00 00 00 00 00 00  01] 00 00 00 00 00 00 0...>
	at net.openhft.chronicle.bytes.UnsafeRWObjectTest.longObject(UnsafeRWObjectTest.java:91)

**Comment by JerryShea** [comment]
This should work now that https://github.com/OpenHFT/Chronicle-Core/issues/451 is done. Please reopen if not
