### ISSUE TITLE
NativeBytesStoreTest fails on Mac OS X with Intel processor

### ISSUE THREAD

**Issue by pcoppinger** [OpenHFT/Chronicle-Bytes#451]
Received the following error with version 2.24ea0-SNAPSHOT:

[ERROR] Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.321 s <<< FAILURE! - in net.openhft.chronicle.bytes.NativeBytesStoreTest
[ERROR] net.openhft.chronicle.bytes.NativeBytesStoreTest.testElasticByteBuffer  Time elapsed: 0.077 s  <<< FAILURE!
java.lang.AssertionError: expected:<32768> but was:<28672>
	at net.openhft.chronicle.bytes.NativeBytesStoreTest.testElasticByteBuffer(NativeBytesStoreTest.java:186)
	
The underlying cause, seems to be related to an error in Chronicle-Core, which was reported earlier (Issue #451).

**Comment by JerryShea** [comment]
This should work now that https://github.com/OpenHFT/Chronicle-Core/issues/451 is done. Please reopen if not
