### ISSUE TITLE
reference to DirectBuffer doesn't compile by default in Java 9+

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#465]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24ea1](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24ea1), [BOM-2.24ea9](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea9)
