### ISSUE TITLE
vectorisedMismatch falsely equates single character strings

### ISSUE THREAD

**Issue by nicktindall** [OpenHFT/Chronicle-Bytes#469]
When `BytesStore#contentEquals` is performed using vectorised mismatch (Java 11+ with `--illegal-access=permit --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-exports java.base/jdk.internal.util=ALL-UNNAMED`) and the two strings are single character, it always returns true regardless of if they are the same character.

**Comment by nicktindall** [comment]
It's breaking the following tests:

https://teamcity.chronicle.software/test/-7506061407356869674?currentProjectId=Chronicle_BuildAll_Checks

https://teamcity.chronicle.software/test/-878476738362959368?currentProjectId=Chronicle_BuildAll_Checks

It's only popped up now because I bumped the parent POM which added the requisite JVM args to enable this behaviour

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23.33](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23.33), [BOM-2.23.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.134)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24ea1](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24ea1), [BOM-2.24ea9](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea9)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.22.29](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.22.29), [BOM-2.22.172](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.172)
