### ISSUE TITLE
Improve Bytes performance tests

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#472]
1. ensure they show up in [TC statistics panel](https://teamcity.chronicle.software/project/Chronicle_ChronicleBytes?projectTab=stats&branch=%3Cdefault%3E#all-projects)
2. make sure all JLBH tests ran
3. extra specialisations of ContentEqualsJLBHTest for smaller size and also compare vs non-vectorized

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24ea7](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24ea7), [BOM-2.24ea47](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea47)
