### ISSUE TITLE
RandomDataInput.copyTo(ByteBuffer) does not use readPosition

### ISSUE THREAD

**Issue by gortiz** [OpenHFT/Chronicle-Bytes#478]
Some time ago @alamar modified Bytes.copy() and Bytes.copyTo(BytesStore) to take readPosition into account (see #300).

But it seems that RandomDataInput.copyTo(ByteBuffer) has the same problem:
- RandomDataInput.copyTo(byte[]) uses readPosition and readRemaining.
- RandomDataInput.copyTo(ByteBuffer) uses readRemaining, but not readPosition (it uses start() instead).
- BytesStore implements RandomDataInput and it has its own copyTo methods, which since #300 use readPosition and readRemaining.

**Comment by alamar** [comment]
Likely fixed in #479 - please recheck @gortiz and reopen if it is not fixed yet.
