### ISSUE TITLE
StreamingInputStream zero length read behaviour

### ISSUE THREAD

**Issue by joncrocks** [OpenHFT/Chronicle-Bytes#48]
The behaviour of StreamingInputStream no longer adheres to the InputStream contract.

From InputStream javadoc.

     * <p> If <code>len</code> is zero, then no bytes are read and
     * <code>0</code> is returned; otherwise, there is an attempt to read at
     * least one byte. If no byte is available because the stream is at end of
     * file, the value <code>-1</code> is returned; otherwise, at least one
     * byte is read and stored into <code>b</code>.

The code to StreamingInputStream was changed as a result of https://github.com/OpenHFT/Chronicle-Bytes/issues/13 so it now returns -1 even the end of the stream has not been reached, if len of 0 is specified.

If 0 is passed into the read of StreamingDataInput, it returns 0 and no bytes have been attempted to be read.

The right fix is probably to add some kind of `if (len == 0) return 0;` statement before an interaction is attempted with the underlying StreamingDataInput.

I encountered this due to it interacting with https://github.com/EsotericSoftware/kryo which I was using to serialise/deserialise objects to be written to a Chronicle Queue. I would admit it's an edge-case and it's slightly strange to request 0 bytes, but going by the Javadoc I would argue there is a bug here in StreamingInputStream.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
