### ISSUE TITLE
NativeStore.wrap(bb) should have a version that does not take possession of bb

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Bytes#486]
ByteBuffer may be on entirely different lifecycle and will not be needing cleanup often.

Map and now FIX are using init() to make such NativeStore's, which should be made protected.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24ea5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24ea5), [BOM-2.24ea44](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea44)
