### ISSUE TITLE
Bytes.toString() fails to rewind NativeBytes

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Bytes#489]
After calling Bytes.toString(NativeBytes) the length of latter is zero (its Store still contains data but it is read out)
toString() should not be a modifying operation. NativeBytes.toString() does not exhibit that behavior.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24ea5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24ea5), [BOM-2.24ea44](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea44)
