### ISSUE TITLE
Support storage of data in lower 31 bits of header while it is being written to

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Bytes#49]

**Comment by epickrram** [comment]
Preparatory work for https://github.com/OpenHFT/Chronicle-Queue/issues/415

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
