### ISSUE TITLE
Translate method in NativeBytesStore

### ISSUE THREAD

**Issue by Neiko2002** [OpenHFT/Chronicle-Bytes#5]
Every read/write method in the NativeBytesStore class calls the translate method, usually nothing happens here except when being a MappedBytesStore. It might be better to either overwrite this method in the MappedBytesStore class and leave it empty in the NativeBytesStore class or to even go further and add an additional class between the MappedBytesStore and the NativeBytesStore. This new class (maybe called SubBytesStore)  would implement all the read/write methods using the translate method and the methods in the NativeBytesStore would not check for translate at all.

**Comment by peter-lawrey** [comment]
translate() should be inlined into the code and if it doesn't do anything it should be eliminated.
Can you clarify what the benefit would be to this change?

**Comment by Neiko2002** [comment]
The body of the translate method in the NativeBytesStore class is simply "return offset - start();". Since start() always returns 0 (except in the case of a MappedBytesStore) the translate call itself does not do anything useful and might slow you down. I don't know if the JIT compiler can optimize this, especially when it has to deal with a polymorphic start method.

**Comment by peter-lawrey** [comment]
For methods we hand optimise we only call thus once eg for UTF8 encoding
and decoding. While I agree it could be faster I would like to see a
benchmark which shows this is what we should be changing.

**Comment by peter-lawrey** [comment]
We have hand optimised some methods when we have identified a performance issue.
Closing for now. Will optimise specific methods are required.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
