### ISSUE TITLE
Add support for reading and writing nested BytesMarshallable objects

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#50]
Added readMarshallableLength16 and writeMarshallableLength16 which uses a 16-bit unsigned length for nested data values.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
