### ISSUE TITLE
Optimisations for Chronicle FIX

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#502]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24ea7](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24ea7), [BOM-2.24ea47](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea47)
