### ISSUE TITLE
Next minor release: change ReadBytesMarsallable.readMarshallable(BytesIn) to use generic

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#51]
This causes some generic method to act as raw ones otherwise.

**Comment by RobAustin** [comment]
@tomshercliff if you want further information on this issue, please contact @peter-lawrey

**Comment by RobAustin** [comment]
Closing as there is not enough detail in the description, please re-open if required, with more details.
