### ISSUE TITLE
ensure that CommonMappedBytes.backingFileIsReadOnly is true if you open a readOnly view of a writeable file

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#519]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24ea12](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24ea12), [BOM-2.24ea65](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea65)
