### ISSUE TITLE
Resource leak in MappedFile

### ISSUE THREAD

**Issue by epickrram** [OpenHFT/Chronicle-Bytes#52]
`acquireByteStore()` erroneously takes a reference to the acquired BytesStore

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
