### ISSUE TITLE
Bytes.append(double) output scientific notation (more eager than expected)

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Bytes#523]
The behaviour of `AbstractBytes.append(double)` has changed in #502 (PR #507)

Previously, `bytes.append(2e-8)` would append `0.00000002`. It now uses scientific notation.

The method is documented in ByteStringAppender as “Appends a double in decimal notation”.

The difficulties are the following:
For some double values, it would become untenable to render them in decimal notation, as they may become circa 400 decimal positions long, so we will likely still drop to scientific notation at some point (and update the javadoc, hopefully).
We also want to avoid showing quantization artifacts and continuous fractions for a subset of human readable fractions, e.g., we do not want to render `0.0009` as `"0.0008999999999999998"`.
However, the actual limits used are also subject to debate. A suggestion is rounding to between 15 and 18 significant figures if possible instead of switching to scientific notation.

**Comment by alamar** [comment]
Current behavior is due to the use of Core's `net.openhft.chronicle.core.io.UnsafeText#appendDouble`

**Comment by JerryShea** [comment]
Fixed by #526 #529 #530
