### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Bytes#538]
Add further tests for `BinaryLengthLength` and `BytesUtil`

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24ea16](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24ea16), [BOM-2.24ea74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24ea74)
