### ISSUE TITLE
Bytes::clear now thread confined!?

### ISSUE THREAD

**Issue by JohannesLichtenberger** [OpenHFT/Chronicle-Bytes#542]
Just curious why you have to clear the instance from the same thread. In my case it means I have to create garbage (as I'd otherwise clear the `Bytes` instance from the wrong thread). Maybe the option to check the thread should stay at least also in future releases?

**Comment by alamar** [comment]
`clear()` is an operation that modifies `Bytes` so it's apparent that it should be single thread checked. We do not expect that you would need to modify `Bytes` from a different thread.

**Comment by JohannesLichtenberger** [comment]
That said I'd simply close it from another thread, but will definitely not access it from another in the same time (so only one at a time). Similar to the new Foreign Memory API / MemorySegments from project Panama

**Comment by alamar** [comment]
Closing/releasing `Bytes` from another thread is a different kind of operation. Closing/releasing implies that no parallel access to the resource is happening. `clear()` is a regular data modifying operation.

**Comment by JohannesLichtenberger** [comment]
Yes, sorry, there's no `Bytes::close` method? I meant clearing. If I as the client make sure, that no other thread is concurrently and in parallel accessing the `Bytes` instance it should be no problem to clear from another thread!? Something like hand over ownership...

**Comment by alamar** [comment]
If you need to hand over ownership, you can call `singleThreadedCheckReset()` before doing `clean()` in another thread. It will jump threads.
