### ISSUE TITLE
Version 2.23.39 not available on Maven Central

### ISSUE THREAD

**Issue by iNikem** [OpenHFT/Chronicle-Bytes#557]
I use `chronicle-bom` to manage versions of all chronicle artefacts. When I use the latest 2.23 version `2.23.189`, my build fails with `The following artifacts could not be resolved: net.openhft:chronicle-bytes:jar:2.23.39`. And indeed, it seems that Maven has 2.23.33 as the latest 2.23 version for `chronicle-bytes`: https://search.maven.org/artifact/net.openhft/chronicle-bytes.

Is it expected that BOM file has non-resolving artefacts? How should I use it then?

**Comment by JerryShea** [comment]
@iNikem please use stackoverflow for questions and github for issues. [Chronicle does not publish stable releases to maven central, only to Chronicle's nexus server](https://github.com/OpenHFT/OpenHFT/blob/develop/docs/Version-Support.adoc#ea-early-access)
