### ISSUE TITLE
Calling MappedBytes.mappedBytes() with readOnly=true leaves realReadRemaining to 0

### ISSUE THREAD

**Issue by vinjana** [OpenHFT/Chronicle-Bytes#561]
In a fresh read-only `ChunkedMappedBytes` created with the factory method `mappedBytes(File, long, long, boolean)`, the `writePosition` will be set to zero by default.

This is o.k. _per se_ but it implies that the `readRemaining()` value will be `0`. So, without further setting the `writePosition`, the new read-only Bytes is unusable. It's not a bug, just kind of unintuitive to having to set `writePosition` on a read-only Bytes.

Maybe it would be better to set the `writePosition` to the file's end if `readOnly` is `true`. Maybe it would help to document this somewhere, e.g. with an example in the readme, or in the method's documentation. Maybe the (new) library user can be forced to think about the issue, by adding initial read and write positions to the method's signature.

**Comment by JerryShea** [comment]
Assigning to you @peter-lawrey to decide what to do

**Comment by yevgenp** [comment]
Hi @vinjana. 
Creating a **read-only** `MappedBytes` implies no write operation is allowed on the instance/file (regardless of the write position returned). Thus setting `writePosition` makes no sense. 
`readRemaining()` works as specified in the JavaDoc and returns `The number of bytes that can still be read.`
Thus there is contradiction/counterintuitive behavior.
