### ISSUE TITLE
BytesMarshaller to support serialisation of null Bytes

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#58]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
