### ISSUE TITLE
BytesMarshaller serialises char using read/writeStopBit instead of String (which was garbagy)

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#59]
Note that this change breaks binary compatibility with previously serialised byte buffers but gives 2 benefits:
- no garbage
- uses less space (1 byte instead of 2 for an 8bit char)

@RobAustin @peter-lawrey should we wait for the next point release to introduce a breaking change like this? I can always parameterise

**Comment by JerryShea** [comment]
Have bumped version from middle version number - now is 1.**_12_**.5-SNAPSHOT and will shoot email around to warn folks of breaking change

**Comment by RobAustin** [comment]
I think it should be 1.12.0-snapshot.

**Comment by JerryShea** [comment]
Yes you are right - I actually used 1.12.1-snapshot in the end (wasn't
thinking straight)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
