### ISSUE TITLE
Option to truncate MappedFile

### ISSUE THREAD

**Issue by kosiakk** [OpenHFT/Chronicle-Bytes#60]
I'm using Bytes as an amazing replacement for `ByteBuffer`, in order to produce large output files of a specific binary format.

Only one thing is missing right now:  once I've finished writing all the data, the file still contains a bunch of zeros at the end - unused data from the last page, between `writePosition` and `realCapacity`. Those zeros are implicitly present in `ElasticBytes`, of course, but I need to truncate the actual file to the correct size.
For example:
```
out.writeLimit(out.writePosition())
```
This might actually go ahead and call `MappedFile.fileChannel.truncate( writeLimit() )`

Since the `fileChannel` is private, now I have to create a new `Channel` and truncate it instead, after releasing Bytes.

**Comment by kosiakk** [comment]
Depending on the luck, I get an error from `truncate` operation: `The requested operation cannot be performed on a file with a user-mapped section open`

**Comment by RobAustin** [comment]
which OS are you using, I think windows will report the full size of the memory mapping, where as linux will show you the space actually used.
