### ISSUE TITLE
Improve accuracy of Bytes.append(double d, int decimalPlaces) when a large number of decimal places is required

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Bytes#600]
When the number of decimal places is too large there may be some rounding artifacts present on the decimal generated by 
`Bytes.append(double d, int decimalPlaces)`. This method attempts a fast path translation from double to decimal. In the cases were an accurate translation cannot be made the algorithm from `BigDecimal` will be used instead. Note that in these cases a `BigDecimal` instance will be created.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.23.43](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.23.43), [BOM-2.23.212](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.23.212)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.24.27](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.24.27), [BOM-2.24.104](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.24.104)
