### ISSUE TITLE
Review automated benchmarks for Bytes contentEquals

### ISSUE THREAD

**Issue by tgd** [OpenHFT/Chronicle-Bytes#608]
# Background

We have some good benchmarks for assessing `Bytes#contentEquals` performance. Not all of these are run for every performance build. Ensure that they are all run, taking care to ensure they run across a good number of JVM versions including those where `vectorizedMismatch` is available - JDK11+.

![image](https://github.com/OpenHFT/Chronicle-Bytes/assets/109181/d9a80c9a-90d6-4dcf-b1c0-9dc69c77b677)

**Comment by yevgenp** [comment]
**ALL** of the above mentioned `ContentEqual` benchmarks are being run by both Performance and PerformanceJava17 jobs.
What's the background or scope left here @tgd ?

**Comment by tgd** [comment]
Thanks @yevgenp - background is to make sure that we have a benchmark that is really invoking `vectorizedMismatch` also. 

The intention is to have good evidence to show that **contentEquals** with vectorizedMismatch outperforms alternatives.

https://github.com/OpenHFT/Chronicle-Bytes/blob/f4ee745a50a6302d76db820c52827c478472c7a7/src/main/java/net/openhft/chronicle/bytes/internal/BytesInternal.java#L122

In order to do this we will need one flavour of the benchmark running on Java 9+. Can you check if this is feasible/trivial?

**Comment by yevgenp** [comment]
Added debug statements to prove that `vectorizedMismatch` access is enabled. See [test run](https://teamcity.chronicle.software/buildConfiguration/Chronicle_ChronicleBytes_PerfJava17/998428?buildTab=log&branch=&focusLine=2578&logView=flowAware&linesState=55.57.60.1385).
