### ISSUE TITLE
Added Comparable<> to bytes

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#61]

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-1.12.7 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-1.12.7), BOM-1.15.253 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.253)

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-1.12.7 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-1.12.7), BOM-1.15.259 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.259)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
