### ISSUE TITLE
Add new method to BytesOut to writeDoubleAndInt

### ISSUE THREAD

**Issue by NickWard** [OpenHFT/Chronicle-Bytes#63]
Improve efficiency esp for fix messages where double fields often go along with a number of decimal places by avoiding common overheads.

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-1.12.10 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-1.12.10), BOM-1.15.271 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.271)

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-1.12.10 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-1.12.10), BOM-1.15.272 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.272)

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-1.12.10 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-1.12.10), BOM-1.15.274 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.274)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
