### ISSUE TITLE
Added enhancements to better ensure file handlers are released

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#64]
A client has reported that the file handles are not always being released, as such we have tightened up the code in this area, having said this, its not yet and issue that we have been able to reproduce.

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
