### ISSUE TITLE
Large copy from a byte[] causes a crash

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#66]

**Comment by peter-lawrey** [comment]
A test needs to be added for large reads as well.

**Comment by RobAustin** [comment]
I'll take a look

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
