### ISSUE TITLE
Improve support for stop bit encoded chars

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#71]
Bytes didn't have direct support for chars, rather it used stop bit encoding.

Added two methods writeStopBit(char) and readStopBitChar() to improve support.

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-1.16.17 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-1.16.17), BOM-1.16.102 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.102)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
