### ISSUE TITLE
Port Chronicle-Bytes to C++

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#75]

**Comment by RobAustin** [comment]
I'm going to close this as duplicate as it has been moved to -> https://github.com/ChronicleEnterprise/Chronicle-Queue-CPP

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-2.17.4 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), BOM-2.17.42 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.42)

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-2.17.4 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), BOM-2.17.44 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.44)

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-2.17.4 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), BOM-2.17.46 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.46)

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-2.17.4 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), BOM-2.17.48 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.48)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), [BOM-2.17.50](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.50)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), [BOM-2.17.52](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.52)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), [BOM-2.17.53](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.53)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), [BOM-2.17.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.4](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.4), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
