### ISSUE TITLE
Make BinaryLongArrayReference BytesMarshallable

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#76]

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-1.16.28 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-1.16.28), BOM-1.16.205 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.16.205)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
