### ISSUE TITLE
added -  public Bytes<Underlying> write(@NotNull RandomDataInput bytes);

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#77]

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-2.17.1 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.1), BOM-2.17.16 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.16)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
