### ISSUE TITLE
Optimised nextSetBit to reduce bit set scanning 

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#78]
added:

```
public int nextSetBit(int fromIndex, int to);
```

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-2.17.2 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.2), BOM-2.17.19 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.19)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
