### ISSUE TITLE
Fixed alignment for Text{Int|Long}Reference on ARM

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Bytes#79]

**Comment by hft-team-city** [comment]
Released in Chronicle-Bytes-2.17.3 (https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.3), BOM-2.17.30 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.30)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
