### ISSUE TITLE
EnumInterner calls toString and can get "Not available" when running in debugger #552

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Chronicle-Bytes#81]
Related the quote in #553 "when debugging MappedBytes, it is pain as the toString() or toHexString used by the debugger alter the underlying bytesStore. Now it detects this is happening and returns "Not available"

@peter-lawrey can you show me which toString() implementation was altering the underlying bytesStore? I've written a test (net.openhft.chronicle.bytes.BytesTest#testToStringDoesNotChange) which verifies that bytes and byteStore are not changed by toString().

The reason this interests me is that we don't just call bytes.toString() when debugging - we also call it in other places e.g. EnumInterner & StringInterner and I have just been tearing out my hair trying to work out why an enum was only failing to deserialise when I ran in the debugger.

I am happy to be set straight, but can't see that toString() causes any changes. toHexString is more complex and so I didn't touch that

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.5), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.5), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
