### ISSUE TITLE
Performance regression - related to change for #77

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Bytes#83]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.5), [BOM-2.17.72](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.72)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.5](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.5), [BOM-2.17.74](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.74)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
