### ISSUE TITLE
StreamingOutputStream should not throw exception when calling write(int) with numbers over 255

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Chronicle-Bytes#88]
According to OutputStream javadoc, we should simply ignore higher 7 bytes, but at the moment we throw IllegalArgumentException

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.15](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.15), [BOM-2.17.149](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.149)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.15](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.15), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.15](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.15), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.15](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.15), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
