### ISSUE TITLE
Fixed issue where optimisedWrite() on a resize was using the wrong address

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Bytes#97]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.19](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.19), [BOM-2.17.196](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.196)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.19](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.19), [BOM-2.17.225](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.225)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.17.19](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.17.19), [BOM-2.17.241](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.17.241)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
