### ISSUE TITLE
Turn off a couple of optimisations which are unreliable on Windows

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Bytes#99]

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.40](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.40), [BOM-2.20.60](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.60)

**Comment by hft-team-city** [comment]
Released in [Chronicle-Bytes-2.20.101](https://github.com/OpenHFT/Chronicle-Bytes/releases/chronicle-bytes-2.20.101), [BOM-2.20.134](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.20.134)
